language: generic
sudo: false

env:
    global:
    - BYOND_MAJOR="512"
    - BYOND_MINOR="1463"
    - BUILD_TOOLS=false
    - DM_MAPFILE=""
    matrix:
    - DM_MAPFILE="lolnone"


cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386

before_script:
  - tools/travis/before_build_byond.sh

script:
  - tools/travis/check_filedirs.sh tgmc.dme
  - tools/travis/build_byond.sh
